

### Get All
GET http://localhost:5000/api/v1/tasks
content-type: application/json

{}


###Get One
GET http://localhost:5000/api/v1/tasks/660dc9750672ee676e4e7c4f
content-type: application/json

{}

###Create
POST  http://localhost:5000/api/v1/tasks
content-type: application/json

{
    "name": "task2"
}

### Update
PATCH   http://localhost:5000/api/v1/tasks/660dc9750672ee676e4e7c4f
content-type: application/json

{
    "name": "task2",
    "isComplete": true
}

### Delete
DELETE    http://localhost:5000/api/v1/tasks/660dc9750672ee676e4e7c4f
content-type: application/json

{}